package lab4_2;

// Generated by Selenium IDE
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import static org.assertj.core.api.Assertions.assertThat;
import org.openqa.selenium.By;
import org.openqa.selenium.firefox.FirefoxDriver;

import io.github.bonigarcia.seljup.SeleniumJupiter;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;

import java.util.*;

@ExtendWith(SeleniumJupiter.class)
public class SeleniumIdeTest {
  
  private Map<String, Object> vars;

  @BeforeEach
  public void setUp() {
    vars = new HashMap<String, Object>();
  }

  @Test
  public void test(FirefoxDriver driver) {
    driver.get("https://blazedemo.com/index.php");
    driver.manage().window().setSize(new Dimension(1848, 1053));
    driver.findElement(By.name("fromPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("fromPort"));
      dropdown.findElement(By.xpath("//option[. = 'Boston']")).click();
    }
    driver.findElement(By.cssSelector(".form-inline:nth-child(1) > option:nth-child(3)")).click();
    driver.findElement(By.name("toPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("toPort"));
      dropdown.findElement(By.xpath("//option[. = 'New York']")).click();
    }
    
    driver.findElement(By.cssSelector(".form-inline:nth-child(4) > option:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    
    assertThat(driver.findElement(By.cssSelector("th:nth-child(4)")).getText()).isEqualTo("Departs: Boston");
    assertThat(driver.findElement(By.cssSelector("th:nth-child(5)")).getText()).isEqualTo("Arrives: New York");
    vars.put("price", driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(6)")).getText());
    vars.put("airline", driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(3)")).getText());
    
    driver.findElement(By.cssSelector("tr:nth-child(1) .btn")).click();

    assertThat(driver.findElement(By.cssSelector("p:nth-child(2)")).getText()).isEqualTo("Airline: United");
    assertThat(driver.findElement(By.cssSelector("p:nth-child(4)")).getText()).isEqualTo("Price: 400");
    
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Benny Lenny");
    driver.findElement(By.id("address")).sendKeys("123 Main Avenue");
    driver.findElement(By.id("city")).sendKeys("New York");
    driver.findElement(By.id("state")).sendKeys("New York");
    driver.findElement(By.id("zipCode")).click();
    driver.findElement(By.id("zipCode")).sendKeys("12345");
    driver.findElement(By.id("creditCardNumber")).click();
    driver.findElement(By.id("creditCardNumber")).sendKeys("987654321");
    driver.findElement(By.id("cardType")).click();
    driver.findElement(By.cssSelector("option:nth-child(1)")).click();
    driver.findElement(By.id("creditCardMonth")).click();
    driver.findElement(By.id("creditCardMonth")).sendKeys("6");
    driver.findElement(By.id("creditCardYear")).click();
    driver.findElement(By.id("creditCardYear")).sendKeys("2025");
    driver.findElement(By.id("nameOnCard")).click();
    driver.findElement(By.id("nameOnCard")).sendKeys("Benny Lenny");
    driver.findElement(By.cssSelector(".checkbox")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();

    assertThat(driver.getTitle()).isEqualTo("BlazeDemo Confirmation");
    
    driver.close();
    }
}